version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8

    working_directory: ~/repo

    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - persist_to_workspace:
          root: /home
          paths: circleci

  deploy:
    docker:
      - image: circleci/node:8

    working_directory: ~/repo

    steps:
      - attach_workspace:
          at: /home
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}"" > ~/.npmrc
      - run: npm run semantic-release

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - next
